'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Category
    Public Property CategoryID As String
    Public Property ShortName As String
    Public Property LongName As String

    Public Overridable Property Products As ICollection(Of Product) = New HashSet(Of Product)

End Class
Partial Public Class Customer
    Public Property Email As String
    Public Property LastName As String
    Public Property FirstName As String
    Public Property Address As String
    Public Property City As String
    Public Property State As String
    Public Property ZipCode As String
    Public Property PhoneNumber As String

    Public Overridable Property Invoices As ICollection(Of Invoice) = New HashSet(Of Invoice)

End Class
Partial Public Class Invoice
    Public Property InvoiceNumber As Integer
    Public Property CustEmail As String
    Public Property OrderDate As Date
    Public Property Subtotal As Decimal
    Public Property ShipMethod As String
    Public Property Shipping As Decimal
    Public Property SalesTax As Decimal
    Public Property Total As Decimal
    Public Property CreditCardType As String
    Public Property CardNumber As String
    Public Property ExpirationMonth As Short
    Public Property ExpirationYear As Short

    Public Overridable Property Customer As Customer
    Public Overridable Property LineItems As ICollection(Of LineItem) = New HashSet(Of LineItem)

End Class
Partial Public Class LineItem
    Public Property InvoiceNumber As Integer
    Public Property ProductID As String
    Public Property UnitPrice As Decimal
    Public Property Quantity As Integer
    Public Property Extension As Nullable(Of Decimal)

    Public Overridable Property Invoice As Invoice
    Public Overridable Property Product As Product

End Class
Partial Public Class Product
    Public Property ProductID As String
    Public Property Name As String
    Public Property ShortDescription As String
    Public Property LongDescription As String
    Public Property CategoryID As String
    Public Property ImageFile As String
    Public Property UnitPrice As Decimal
    Public Property OnHand As Integer

    Public Overridable Property Category As Category
    Public Overridable Property LineItems As ICollection(Of LineItem) = New HashSet(Of LineItem)

End Class
